### PR TITLE
Started ToolSearchEngine, returns missbehaving

### PR DESCRIPTION
**Pull request by thok54**
New pull request for the searching tool.

Made some of the changes we talked about. Started to look at the ToolSearchEngine.
search method complains because I´m trying to return a bank/account/payment list instead of an object list.

Sorry for the delay, been a busy week.

### CODE REVIEW

**Review by jantpedraza — CHANGES_REQUESTED** [review]
You have some TODOS pending :)

Review my comments in the commit and apply them. In general, very good job Jesus, but never forget Unit Tests are very very important to make sure your code does what you pretend :)

**Comment by thok54** [comment]
I am still unable to run the program, something about "No tests were found". Not sure if it´s due to something from when I pulled your version of the code.

**Comment by thok54** [comment]
About the InternalDto, when I try to modify the methods to deal with it, I get the same errors I was getting when trying to replace them with Object

**Comment by jantpedraza** [comment]
Jesus, I'm trying to run the program from the `MainProcess` but it doesn't work. Please, review the code and verify that everything works.

I'm getting this error trying to search for BANK: 

```
java.lang.NumberFormatException: For input string: "BANK"
Unable to parse number BANK
[null]
```

**Comment by jantpedraza** [comment]
> I am still unable to run the program, something about "No tests were found". Not sure if it´s due to something from when I pulled your version of the code.

Try to remove the code from your folder and clone again from here.

**Comment by jantpedraza** [comment]
> About the InternalDto, when I try to modify the methods to deal with it, I get the same errors I was getting when trying to replace them with Object

No worries, we will review this in a call.

**Comment by thok54** [comment]
Managed to fix the error I wrote you about by pulling the code. But every time I close InteliJ, a new error seems to pop up, and then I have to pull the version from here and try to repeat all the changes I have done. Not sure if it´s InteliJ, the pong files, or both playing me tricks

**Comment by jantpedraza** [comment]
Jesús, good stuff. Program is working now and searcher also :) Congratulations!!

I will approve this pull request and you can merge, even though some TODOs are still pending, I think it is better to review them in the next skype.

**Review by jantpedraza — APPROVED** [review]

**Pull request merged**
